[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
lazy_static = "1.4.0"
rand = "0.8.5"
cursive = { version = "0.20.0", default-features = false, features = ["crossterm-backend"] }
